# Generated by Django 3.0.7 on 2020-06-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('numero_depot', models.IntegerField(primary_key=True, serialize=False)),
                ('intitule_depot', models.CharField(max_length=100)),
            ],
        ),
    ]
