# Generated by Django 3.0.7 on 2020-08-10 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_devise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_document_app.Devise'),
        ),
    ]
