# Generated by Django 3.0.7 on 2020-06-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.IntegerField(primary_key=True, serialize=False)),
                ('article_ref', models.CharField(max_length=20)),
                ('article_design', models.CharField(max_length=100)),
                ('prix_achat', models.IntegerField()),
            ],
        ),
    ]
