# Generated by Django 3.0.7 on 2020-06-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devise_id', models.IntegerField()),
                ('devise_intitule', models.CharField(max_length=20)),
            ],
        ),
    ]
