# Generated by Django 3.0.7 on 2020-06-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0003_devise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devise',
            name='id',
        ),
        migrations.AlterField(
            model_name='devise',
            name='devise_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
