# Generated by Django 3.0.7 on 2020-08-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0003_auto_20200810_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='article_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_document_app.Article'),
        ),
        migrations.AlterField(
            model_name='document',
            name='departement_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_document_app.Departement'),
        ),
        migrations.AlterField(
            model_name='document',
            name='numero_depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_document_app.Depot'),
        ),
    ]
