# Generated by Django 3.0.7 on 2020-06-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0004_auto_20200630_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('departement_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departement_intitule', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('Famille_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Famille_intitule', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('fournisseur_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('fournisseur_intitule', models.CharField(max_length=20)),
                ('fournisseur_adresse', models.CharField(max_length=20)),
                ('fournisseur_telephone', models.CharField(max_length=20)),
                ('fournisseur_email', models.CharField(max_length=20)),
            ],
        ),
    ]
