# Generated by Django 3.0.7 on 2020-08-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0004_auto_20200810_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_validation',
            new_name='document_validation1',
        ),
        migrations.AddField(
            model_name='document',
            name='document_validation2',
            field=models.BooleanField(default=False),
        ),
    ]
