# Generated by Django 3.0.7 on 2020-08-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0005_auto_20200810_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_MT_HT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_MT_TTC',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_P_U_DEV',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_P_U_HT',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_remise',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_taxe',
            field=models.FloatField(null=True),
        ),
    ]
