# Generated by Django 3.0.7 on 2020-06-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0005_departement_famille_fournisseur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='famille',
            old_name='Famille_id',
            new_name='famille_id',
        ),
        migrations.RenameField(
            model_name='famille',
            old_name='Famille_intitule',
            new_name='famille_intitule',
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='fournisseur_id',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
