# Generated by Django 3.0.7 on 2020-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0006_auto_20200812_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_MT_HT',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_MT_TTC',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_P_U_DEV',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_P_U_HT',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_QT',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_remise',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_taxe',
            field=models.FloatField(default=0, null=True),
        ),
    ]
