# Generated by Django 3.0.7 on 2020-06-30 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_document_app', '0007_auto_20200630_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famille',
            name='famille_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='fournisseur_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
